### ISSUE TITLE
pnpm storybook not work

### ISSUE THREAD

**Issue by buffalo-thb** [illacloud/illa-design#676]
### Description

When I run "pnpm storybook" command, I expected open storybook or something else to happen but happened nothing! I update my node from 14.x.x to 16.x.x, and "pnpm installed" again, but still nothing happened. My system is macOs.

### Link to Reproduction

no link

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### ILLA Design Version

@illa-design/react@1.0.16 Latest on Feb 17

### Browser

Google chrome 111.0.5563.64

### Operating System

- [x] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I want to write this question to community, but I can`t open it.

**Comment by smallSohoSolo** [comment]
please use `pnpm sb` command

**Comment by buffalo-thb** [comment]
> please use the `pnpm sb` command we command to use develop branch to build it.

Thank you, it works! The document was incorrect but I didn`t notice it. 
<img width="610" alt="image" src="https://user-images.githubusercontent.com/20547935/226888598-dce72b52-159a-4c53-aef5-1a8f65a1db24.png">
